version: "3.9"

services:
  namie_cc_web_service:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: namie_cc_web_service:latest
    environment:
      APP_ENV: "development"
      APP_PORT: 8010
      REDIS_HOST: www_redis_normal
      REDIS_PORT: 6379
      MYSQL_HOST: www_mysql_8
      MYSQL_PORT: 3306
      MYSQL_USER: "root"
      MYSQL_PWD: "www_mysql_8"
      MYSQL_DB_NAME: "www_namie_cc"
    expose:
      - "8010"
    networks:
      - webnet
    restart: always
    volumes:
      - "~/data/logs/namie_cc_web_service:/data/log/www.namie.cc"
    # depends_on:
    #   - www_namie_cc_redis
networks:
  webnet:
    name: webnet
    driver: bridge
